version: 1

update_configs:
  - package_manager: "javascript"
    directory: "/"
    update_schedule: "live"
    default_reviewers:
      - "vivek1996"
    default_assignees:
      - "vivek1996"
    version_requirement_updates: "increase_versions"
    commit_message:
      prefix: "feat"
      prefix_development: "chore"
      include_scope: true
